version: '3'
services: 
    api:
        build:
            context: ./catan-api
            dockerfile: Dockerfile
        ports:
            - ${EXTERNAL_API_PORT}:${INTERNAL_API_PORT}
        environment: 
            ASPNETCORE_ENVIRONMENT: ${DOTNETCORE_ENV}
    frontend:
        build: 
            context: ./catan-frontend
            dockerfile: Dockerfile
        ports:
            - ${EXTERNAL_FRONTEND_PORT}:${INTERNAL_FRONTEND_PORT}
        environment:
            NODE_ENV: ${NODE_ENV}
            API_HOST: ${API_HOST}